### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Aaron1011** [NickImpact/Daycare#10]
First of all, thank you for making such a great plugin!

Would you mind adding an explicit license to the project? I'd like to re-use some of your code (with attribution) in my own plugin, but I'm not sure if you'd be okay with that.

**Comment by NickImpact** [comment]
You're free to use and deploy my code however you see fit. Believe I have it set to use GPL-3.0, I just need to actually add the licensing to the files. I've been sorta lazy on doing that part, so if the components you are re-using are the storage or config standards, those would be from Luck, just can't remember if I added his license headers yet.
