### ISSUE TITLE
Daycare Level Reversions

### ISSUE THREAD

**Issue by Corcustos** [NickImpact/Daycare#11]
After some testing I was able to figure out what was causing my daycare levels to revert themselves. If you restart the server while a pokemon that has gained levels is in daycare, that pokemon will revert after taking it out. Works 100% fine if you do not restart the server before taking the pokemon out. Leveling was kept on the entire time, and nothing else was done besides adding pokemon, restarting the server, and removing pokemon. I tested with multiple pens and multiple pokemon just to be sure.

Happens with [minimal plugins](https://i.imgur.com/6PNn2B6.png) on the server on latest versions and a fresh set of daycare+impactor installations. This leads me to believe it's an actual bug with Daycare, which is why I made this ticket. Unfortunately, there were no daycare related error messages to be seen. I checked console, latest.log, and debug.log and looked at all messages that had the word "daycare" in them..

Forge is 2809 and SpongeForge is RC3616. I believe everything else was up-to-date that needed to be.

**Comment by NickImpact** [comment]
Thanks for the note on this, got swept away in my notifications at first. I'll look into what is going on with this, but I have a sneaky suspicion as to what it is without looking at the code yet.
