### ISSUE TITLE
Broken conditional evolutions and server errors preventing leveling.

### ISSUE THREAD

**Issue by Corcustos** [NickImpact/Daycare#5]
I've been testing various conditional evolutions in the daycare, and it seems that most of them are broken. These are the issues that I have found with this so far:

Male Combee evolves into Vespiquen.
Male Burmy evolves into Wormadam instead of Mothim.
All Tyrogues evolve into Hitmonlee regardless of stats.

I planned to do more testing with things such as required-move evos, but I encountered an [issue](https://hastebin.com/) that told me leveling was disabled until the next restart. I thought I'd bring this issue up regardless. If need be I can continue testing with a few other types of conditional evolutions after a server restart.

I am using SF 3206, Pixelmon 6.3.4, and Daycare 0.10.1.

**Comment by NickImpact** [comment]
Finally, a bug report! Anyways, just seems like there’s more to level evolution setups than I first realized or remembered. Hopefully should be an easy fix.

As for the leveling stopping thing, it’s because the evolution tree found a null evolution in its path. Still not sure how it happens, but we don’t want to try evolving into nothing

**Comment by NickImpact** [comment]
There’s clearly something wrong with external information on evolution data it seems. I believe wiki is in pixel extras, and if it’s suffering from the same issue, then there’s something nasty in play. For /wiki, it’d be up to just the writers of the command to fix it, there’s nothing you can do. Hopefully I’ll figure out how to avoid this null encounter, and they can pull from me.

**Comment by Corcustos** [comment]
Alright, if there's anything else you need me to do or provide let me know.

**Comment by NickImpact** [comment]
There is one thing. When the wiki reported null evolutions, was the proper evolution following it?

**Comment by Corcustos** [comment]
If you're asking whether or not the pokemon properly evolved into null-reported evolutions without daycare, yes. Burmy did even while in the daycare, and 2 Tyrogues did once before giving errors. Other than the one time that Tyrogue errored, there were no issues with null evolutions.

**Comment by NickImpact** [comment]
Believe I have a fix for it. Also should no longer experience the disabled leveling feature as this should work around it.
